#!/bin/bash
#
# firstboot: Invokes the oracle-rdbms-server-11gR2-preinstall-firstboot checkboot 
#            function if it hasn't been run before
#
# Copyright (C) 2006 Oracle. All rights reserved.
#
# chkconfig: 2345 99 95 
#
# description:       oracle-rdbms-server-11gR2-preinstall runs to modify boot parameters
#
# Source function library.
. /etc/init.d/functions

FILENAME=/etc/sysconfig/oracle-rdbms-server-11gR2-preinstall/oracle-rdbms-server-11gR2-preinstall.conf;
PRE_PARAM_LOG=/var/log/oracle-rdbms-server-11gR2-preinstall/results/orakernel.log;
LOCKFILE=/var/lock/subsys/oracle-rdbms-server-11gR2-preinstall;

case "$1" in
 start)
	[ -f "$LOCKFILE" ] && exit 0

	if [ -f "$FILENAME" ] && /bin/grep -q '^RUN_11GR2_PREINSTALL=NO' "$FILENAME"; then
		action=skip
	else
		action=run	
        fi

	[ $action = skip ] && exit 0

	if [ $action = run ]; then
		/usr/bin/oracle-rdbms-server-11gR2-preinstall-verify -b 2> /dev/null 1>&2
		RETVAL="$?"
	fi
		        
	if [ "$RETVAL" -eq 0 ]; then
	        echo "Altered Boot file /boot/grub/grub.conf and will be effected on next reboot" >> ${PRE_PARAM_LOG}
		action "" /bin/true
        else
		echo "Boot file /boot/grub/grub.conf modifications failed" >> ${PRE_PARAM_LOG}
		action "" /bin/false
        fi

	/bin/touch $LOCKFILE

        ;;
 stop)
	/bin/rm -f $LOCKFILE
   ;;

 *)
   echo $"Usage: $0 {start|stop}"
   RETVAL=1
esac
	
exit $RETVAL

